apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: loadgenapp
  name: loadgenapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: loadgenapp
    spec:
      containers:
      - image: docker.io/library/go-loadgen:latest
        name: go-loadgen
        ports:
          - containerPort: 8080
        resources: {}
status: {}
